adicionar conteúdo da semana 02
ftonato/Web-I pull request #1
Opened 2017-10-19 17:13 UTC by ftonato

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/README.md
> +Na semana seguinte, vocês serão capazes de criar uma página HTML estilizada com CSS, e será o ponto de partida para aquilo que aprenderemos ao longo do curso...
Não é o desafio dessa semana?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/README.md
> +﻿# Semana 02
Não sei o que seria melhor.... mas o que acha de mudar o conteúdo da primeira semana? Algo como sobre o que é a web, a internet e tudo mais.... Não estou achando os links agora, mas algo nesse sentido. Talvez até deixar aquele link e adicionar essas coisas.

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/README.md
> +**CSS**
O que acha de quebrar o HTML e CSS. Nessa semana falar só sobre o HTML, como colocar textos na tela e na próxima semana falar sobre como mudar os textos que já estão na tela?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/README.md
> +Como já devem saber, vocês devem executar esses arquivos em seus navegadores para que seja possível ver eles funcionando, recomendo os seguintes navegadores: Mozilla Firefox, Google Chrome, Opera, e
O que acha de aqui, falar que o "executar" nada mais é do que abrir o arquivo usando o navegador?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/README.md
> +- Primeiramente vocês devem abrir o arquivo com algum editor de texto que preferirem (pode ser o [Notepad++](https://notepad-plus-plus.org/));
o que acha de indicar o sublime? ele é tão fofoo ❤️

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/desafio.html
> +<html lang="en">
aqui o `lang` seria `pt-BR` não?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/desafio.html
> +				Deixe essas regras aqui :)
Aqui não seria interessante falar que é um comentário em CSS também?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/exemplo.html
> +<html lang="en">
aqui o `lang` seria `pt-BR` não?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/exemplo.html
> +		h1 {
essas duas propriedades são realmente necessárias? Por padrão já é assim, não?

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/exemplo.html
> +		/* Definindo a cor do subtítulo da página */
a cor e o alinhamento *

2017-10-19 22:37 UTC, FernandaBernardo commented on Semana 02/desafio/exemplo.html
> +	<div class="footer">
Acha que usar uma tag footer aqui é avançado demais?

2017-12-08 23:38 UTC, FernandaBernardo requested changes

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 02/desafio/README.md
> +**Dica:** Para conseguir fazer as edições no arquivo, é preciso abrir o arquivo com um editor de texto (recomendo o [Sublime Text](https://www.sublimetext.com/)).
Diga todos ;P Atom, VSCode, blablabla

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 02/desafio/desafio.html
> +    <style>
Já que essa semana é só de HTML, não seria interessante apagar o CSS? Do `exemplo.html` também

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 02/desafio/exemplo.html
> +	<div>
`div` :(

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 03/desafio/desafio.html
> +        /* Deixe essas regras aqui, elas serão explicadas futuramente! */
Acho que já que ainda não cabe aqui, pode ser removido... o "reset" não é realmente necessário agora

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 03/desafio/desafio.html
> +    <!-- Isso é um comentário HTML, defina abaixo aquilo que foi solicitado no desafio -->
Aqui você poderia trocar o comentário, dizendo que aqui tem todos os elementos que o aluno colocou no desafio passado

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 03/desafio/exemplo.html
> +			/* Essa é uma regra atribuída a todos os componentes da nossa página */
Mesma coisa do reset aqui

2017-12-08 23:38 UTC, FernandaBernardo commented on Semana 03/desafio/exemplo.html
> +	<div class="footer">
porque não apresenta a tag `footer`?

2017-12-12 13:27 UTC, ftonato commented on Semana 02/desafio/exemplo.html
> +	<div>
`div's` são legais (as vezessssssss)

2017-12-12 13:44 UTC, merged